-- 创建回测统计信息表
CREATE TABLE IF NOT EXISTS backtest_statistics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id VARCHAR(50) NOT NULL UNIQUE,
    backtest_id VARCHAR(50) NOT NULL,
    total_signals INTEGER DEFAULT 0,
    buy_signals INTEGER DEFAULT 0,
    sell_signals INTEGER DEFAULT 0,
    executed_signals INTEGER DEFAULT 0,
    unexecuted_signals INTEGER DEFAULT 0,
    execution_rate REAL DEFAULT 0.0,
    avg_signal_strength REAL DEFAULT 0.0,
    total_trades INTEGER DEFAULT 0,
    buy_trades INTEGER DEFAULT 0,
    sell_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    win_rate REAL DEFAULT 0.0,
    avg_profit REAL DEFAULT 0.0,
    avg_loss REAL DEFAULT 0.0,
    profit_factor REAL DEFAULT 0.0,
    total_commission REAL DEFAULT 0.0,
    total_pnl REAL DEFAULT 0.0,
    avg_holding_days REAL DEFAULT 0.0,
    total_stocks INTEGER DEFAULT 0,
    profitable_stocks INTEGER DEFAULT 0,
    avg_stock_return REAL DEFAULT 0.0,
    max_stock_return REAL,
    min_stock_return REAL,
    first_signal_date TIMESTAMP,
    last_signal_date TIMESTAMP,
    first_trade_date TIMESTAMP,
    last_trade_date TIMESTAMP,
    trading_days INTEGER DEFAULT 0,
    unique_stocks_signaled INTEGER DEFAULT 0,
    unique_stocks_traded INTEGER DEFAULT 0,
    most_signaled_stock VARCHAR(20),
    most_traded_stock VARCHAR(20),
    max_single_profit REAL,
    max_single_loss REAL,
    max_consecutive_wins INTEGER DEFAULT 0,
    max_consecutive_losses INTEGER DEFAULT 0,
    largest_position_size REAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_statistics_task_id ON backtest_statistics(task_id);
CREATE INDEX IF NOT EXISTS idx_statistics_backtest_id ON backtest_statistics(backtest_id);
